export const IS_FETCHING_PRODUCTS = "IS_FETCHING_PRODUCTS";
export const IS_FETCHING_BRIEFS = "IS_FETCHING_BRIEFS";
export const RECEIVED_PRODUCTS = "RECEIVED_PRODUCTS";
export const RECEIVED_BRIEFS = "RECEIVED_BRIEFS";
export const ADD_BRIEF = "ADD_BRIEF";
export const HAS_UPDATED = "HAS_UPDATED";
